title: Nazzareno Massari
url: http://naszam.io
description: All content written by me is by default released freely under the [WTFPL](http://www.wtfpl.net/).
github_username: naszam
twitter_username: NazzMass
markdown: kramdown
