title: Nazzareno Massari
url: http://naszam.io
description: All content written by me is by default released freely under the <a href:"http://www.wtfpl.net/">WTFPL.</a>
github_username: naszam
twitter_username: NazzMass
markdown: kramdown
